site_name: LIMSport
site_author: Theiagen Genomics
site_description: LIMSport reads a TSV of samples, applies an optional YAML config to rename/select columns and run QC on each row, and writes a LIMS-importable TSV.

site_url: https://theiagen.github.io/limsport/
edit_uri: "edit/main/docs/"

repo_url: https://github.com/theiagen/limsport

nav:
    - LIMSport: index.md
    - ConfigBuilder: config.md

theme:
  variant: classic
  logo: theme/logos/Theiagen-Logo-White.png
  favicon: theme/logos/Theiagen-Symbol-Standard-01.png
  custom_dir: docs/theme/overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.follow
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: indigo
      primary: black
      toggle:
        icon: material/white-balance-sunny
        name: Switch to Light Mode


extra_css:
  - theme/stylesheets/extra.css

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - mike:
      canonical_version: null

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:<support@theiagen.com>
      name: Talk with us
    - icon: fontawesome/brands/github
      link: https://github.com/theiagen
      name: Code with us
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/theiagen.bsky.social
      name: Tweet with us
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/theiagen
      name: Connect with us
  version:
    provider: mike
    default: latest
    alias: true
  homepage: https://www.theiagen.com

# remove once hooks are supported
copyright: |
  &copy; 2022-2026 <a href="https://www.theiagen.com" target="_blank" rel="noopener">Theiagen Genomics</a>

# currently unsupported in zensical
#hooks:
#  - theme/macros/hooks/on_config.py
